# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 438cc10d6d691c47faf50d59533bfa96bcbf7ce7102c7595968e30047ba620f140a36499a534b6251ff48ac902570319e4af183513cf6060782df9335af67eea

test:
  secret_key_base: a10be1d6b18a652be099cc26e506f7d60c6be95d78da351bdef0b4d0ec4c8976e2dddc8f147798e15028376d935ec013b74a2e99d0ce35d317bd43ebe258043a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
